geerlingguy/ansible-role-php

tasks/setup-Debian.yml

Run apt-get update before fetching php packages.

Avoid expired caches

---

defaults/main.yml
templates/php.ini.j2

I think it's an important setting, specially for security. Since I needed it, I made a pull request at the same time.

Add option to disable expose_php

---

README.md

Just updates the readme to change some references to APC in the Opcache section (I'd guess relics from copy & paste).

Fixed typos in the Opcache section

---

tasks/configure.yml
vars/Debian.yml
vars/RedHat.yml

Allow overriding `php_fpm_daemon` in a similar way to other vars.

Allow overriding php_fpm_daemon

---

README.md

* add link to referenced roles
* use remi-php56 as example (instead of EOL php 5.4)

Improve repo description

---

tasks/configure-fpm.yml
vars/Debian.yml
vars/RedHat.yml

Unfortunately Debian likes to have everything PHP5 related in a PHP5 directory, so in-order to get this role working with PHP 7, yet another path has to be configurable!

Made php_fpm_pool_conf_path configurable - for PHP 7.

---

defaults/main.yml
templates/opcache.ini.j2

New config item `php_opcache_blacklist_filename` for defining an opcache blacklist file. The config item is optional.

Add option for opcache blacklist file

---

defaults/main.yml
templates/php.ini.j2

Proposed changes make it possible to configure session related time limits and session garbage collection parameters in php.ini. For example, on Debian derivatives there is a separate cron job that takes care of cleaning up the session data so disabling the gc makes sense if that's left in place.

Configuration options for PHP session handling.

---

vars/Debian.yml

This is a mergable PR for #82. I want to keep the old PR for historical reference in case we need to do similar scenario testing again. This works for all distros:
- Apache with `mod_php`
- Apache with PHP FPM (not on Centos 6 because the test setup is complex, this bug fix doesnt adress centos anyway)
- Nginx with PHP FPM
- No webserver (applies to the CLI php).
I feel this is the best approach as a configuration change and a re-provision would create the new ini only if necessary. Instead of bloating the configs or complicating the role unnecessarily (trying to create apc/opcache ini files for all directories would be a nasty `with_nested` task). 
The docker build for PHP FPM only pass on Ubuntu 14.04 with the custom initctl mentioned …

Closes #53, #60: Fix php.ini not applied for php-fpm on ubuntu

---

tasks/configure-fpm.yml
templates/www.conf.j2
vars/Debian.yml
vars/RedHat.yml

Fix issue #120, by introducing variables for the FPM pool user and group, and templating the default pool configuration to pull them in.
Comments and suggestions welcome.

Fix #120: Introduce variables for FPM user and group.

---

README.md
defaults/main.yml
tasks/configure.yml
templates/apc.ini.j2
templates/opcache.ini.j2

[Related to this issue](https://github.com/geerlingguy/ansible-role-php/issues/130) and [this one](https://github.com/geerlingguy/ansible-role-php/issues/48), I thought some tweaks needed to be made with configuration file management for apc and opcache.  The fix is simply to remove any apc or opcache configuration files that the PHP installation creates in favor of managing the configuration files through this role.
Another change is to remove the variables `php_opcache_enabled_in_ini` and `php_apc_enabled_in_ini` and just rely on the switches `php_opcache_enable` and `php_enable_apc` to create or remove the relevant config files.  I think this should suffice unless I'm missing something.  Just let me know.
For the sake of noting everything related going on the repo, it looks like [this …

Fixes #130 and #48: Tweak and simplify some of the apc and opcache configuration

---

defaults/main.yml
templates/php.ini.j2

According to phpsec.org (http://phpsec.org/projects/phpsecinfo/tests/allow_url_fopen.html), php_allow_url_fopen should be disabled for security reasons.
It's also recommended to be disabled for Drupal installations (https://www.drupal.org/requirements/php).
I've created a variable "php_allow_url_fopen" and set the default to "Off". This allows the user to override the value if they desire.
Builds successfully using Travis CI (https://travis-ci.org/csedev/ansible-role-php/jobs/80001558)

Variable to enable / disable php_allow_url_fopen

---

README.md
defaults/main.yml
templates/opcache.ini.j2

Here is the original problem for anyone having the same issue: There was this error when trying to run php in Centos7. 
`Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory`
Fixed it by installing php56-php-opcache from remi-php56 repo and specifying full path as zend_extension:
`php_opcache_zend_extension: "/opt/remi/php56/root/usr/lib64/php/modules/opcache.so"`

add support to set custom opcache.so location

---

defaults/main.yml

https://secure.php.net/manual/en/ini.core.php#ini.short-open-tag
The value should be "Off" instead of "False". This was changed in the pull request making the variable configurable: https://github.com/geerlingguy/ansible-role-php/pull/7/files

Changed default value of short_open_tags to Off instead of False

---

README.md

Hey there. Just followed the tip about adding additional config to www.conf, but the instructions probably point to the wrong file? Anyway, I found it more helpful to look at configure-fpm.yml, so I am assuming this is what people should look at to alter that file.
Thanks for making this, btw!

Change README to point to correct lineinfile hint

---

tasks/configure-opcache.yml
tasks/setup-Debian.yml

When running the role, I'm getting a deprecation warning:
```
TASK [geerlingguy.php : Ensure OpCache config file is present.] ****************************************************************************************
[DEPRECATION WARNING]: evaluating 1 as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future.
Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
This fixes by using the `bool` filter to convert the variable to a boolean for conditional checks.

Use |bool filter on opcache variable to avoid deprecation warning

---

templates/php.ini.j2

https://www.php.net/manual/en/ini.core.php#ini.asp-tags
https://www.php.net/manual/en/ini.core.php#ini.always-populate-raw-post-data
https://www.php.net/manual/en/session.configuration.php#ini.session.bug-compat-42
https://www.php.net/manual/en/session.configuration.php#ini.session.bug-compat-warn
Removing them since this role/php only supports [7.1+](https://php.net/supported-versions.php)

Remove settings which are absent in php 7.0+

---

vars/RedHat.yml

php-imap is not available anymore.. it was epel7 and will not be included in rh8

Removing php-imap from RedHat vars

---

README.md
defaults/main.yml
handlers/main.yml

In production systems, it is sometimes better to reload FPM instead of
restarting. This commit allows users to manage restart or reload of php-fpm
service, but keeps restarting by default.
Co-authored-by: Julien LE SAUX <julien.le.saux@fr.clara.net>

Added possibility to choose if php-fpm is restarted or reloaded.

---

defaults/main.yml
templates/php.ini.j2

According to the php documentation, the default version for php should be "-1". Before php7.1 it was 17, so I parameterized it, and made the default "-1"
see https://www.php.net/manual/en/ini.list.php

Make serialize_precision a parameter

---

tasks/main.yml

I found out I was unable to specify 7.3 on an Ubuntu 18 installation, and it stemmed from a clean up that enforced the default version being configured on Debian based systems.

Allow the php version to be overridden.

---

README.md
defaults/main.yml
tasks/configure-fpm.yml
templates/www.conf.j2

Allow to configure extra fpm pools with a generic template.
You can find an example of php_fpm_extra_pools usage in default vars.
pool_name and pool_listen are mandatory.

Configure extra fpm pools

---

defaults/main.yml

make #302 backwards compatible, fixes #329
based on comment from https://github.com/geerlingguy/ansible-role-php/pull/302#issuecomment-741609370

Use former pool values in multi-pool config

---

.github/workflows/ci.yml
vars/Debian-11.yml

Hi @geerlingguy, I recently tried to use this library with Debian 11 and it wasn't working without this variable.
Defining the variable myself solve the build, so I suppose there is nothing more to do.

Add support for Debian 11

---

.github/workflows/ci.yml
meta/main.yml
vars/Ubuntu-22.yml

...and remove trusty from meta file since it is already no longer supported
/cc @geerlingguy

add support for Ubuntu 22.04 (jammy)

---

tasks/main.yml
vars/Debian.yml

Starting with PHP 8.0 the JSON extension is part of the base package and cannot be installed separately.
Fixes #358

Only install the JSON extension on Debian for PHP 7.4 and below

---

handlers/main.yml
tasks/configure-fpm.yml

At the moment running the role when in check mode always fails since the role is trying to start/restart `php-fpm` service. This will never succeed in check mode since no real changes are made to the target environment. 
This change ensures that both `restart php-fpm` and `Ensure php-fpm is started and enabled at boot (if configured).` do not run in check mode.
Below is steps I took to reproduce the issue on Ubuntu 20.04
- Run ` ansible-playbood --check --diff`
Output:
```TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ***
fatal: [***]: FAILED! => {"changed": false, "msg": "Could not find the requested service php8.1-fpm: host"}
```
Definition:
```
php_default_version: "8.1"
become: true
daemon_reload: yes
vars:
php_fpm_daemon: "php8.1-fpm" …
```

Do not run php-fpm service when ansible is in check mode

---

tasks/configure.yml

Current Ansible version that is for example in AWX does not have `with_flattened` anymore.
The fix is rather simple, but i would recommend that you check your other (great) ansible roles too.
BTW i have also corrected module names to fully qualified names, as recommended by current ansible-lint - at least for this file only. Hope this will be OK.
Ps. I wondered if for those variables we need to flatten at all, since those are plain, non-nested lists and you use them inside {{}} brackets. Anyway i did apply flatten as it won't hurt.
Ps. really great set of ansible roles - very well thought.

fix with_flattened

---

README.md
defaults/main.yml
templates/www.conf.j2

Makes it possible to define a status_path. The default value is empty, and in that case the setting will not be written to the config file, i.e. no change to default behaviour.
for your consideration @geerlingguy

add option to set pm.status_path
